config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path("product/", include("cms.products.urls", namespace="products")),
    # User management
    path("users/", include("cms.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

crm/blog/urls.py
from django.urls import path
from django.views.generic.base import View
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('<id>/',views.SingleBlogView.as_view(), name='single_blog' ),
    path('topic/<slug:slug>', views.CatagoryView.as_view(), name='catagory'),
    path('tag/<int:id>', views.TagView.as_view(),name='tag'),
    path('subscribe/', views.SubsCribe.as_view(), name='subscribe'),
    path('search/',views.SearchView.as_view(), name='search'),
    path('<int:id>/create-comment/',views.CommentView.as_view(), name='comment'),

    # test
    path('test/', views.test, name='test'),

]

crm/quotes/urls.py
from django.urls import path
from . import views
app_name="qoutes"
urlpatterns = [
    path('', views.qoutes, name='scraper'),
    # Post 
]

crm/users/urls.py
from django.urls import path

from crm.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)
from crm.users.api.views import UserList,UserDetail
app_name = "users"
urlpatterns = [
    path("list/", UserList.as_view() , name="list"),
    path("detail/<id>/", UserDetail.as_view() , name="UserDetail"),

    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

crm/chatgpt/models.py
from django.db import models

# Create your models here.

crm/quotes/models.py
from django.db import models

class Quotes(models.Model):
    author = models.CharField(max_length=50)
    text = models.TextField(unique=True)

    def __str__(self):
        return self.text

crm/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

crm/blog/views.py
import blog
from django import views
from django.core import paginator
from django.http import HttpResponseRedirect
from django.db.models.fields import EmailField
from django.shortcuts import render, redirect,get_object_or_404
from django.views import View
from crm.blog.models import Blog, Catagory,Tag, EmailSignUp,Comment
from django.core.paginator import Paginator
from django.db.models import Count 
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q

from crm.quotes.models import Quotes

def HomePage(request):
    
    data= list(Quotes.objects.all().order_by('-id'))
    context={

        'data':data,
    }

    return render(request,"pages/home.html",context )



class HomeView(View):
    def get(self,request,*args,**kwargs):
        '''
        # featured_post = Blog.objects.filter(featured=True, status='active',show_hide='show').order_by('-id')
        # catagories_obj  = Catagory.objects.all().order_by('-id')
        # tags_obj = Tag.objects.all().order_by('-id')
        # blog_post  = Blog.objects.filter(status='active',show_hide='show').order_by('-id')
        # popular_post = blog_post[:3]
        # images_obj = blog_post.only('image').order_by('-id')[:6]
        # #all_post = Blog.objects.all().order_by('-id')
        # # pagination Logics
        # paginator = Paginator(all_post, 4)
        # page_number = request.GET.get('page')
        # page_obj = paginator.get_page(page_number)

        # context = {
        #     'featured':featured_post,
        #     'popular': popular_post,
        #     'catagories':catagories_obj,
        #     'tags':tags_obj,
        #     'image':images_obj,
        #     'post':page_obj

        # }
        '''
        featured_obj = Blog.objects.all().filter(status='active', visible=True, featured=True).order_by('catagories','-created_at')[:5]
        post_obj = Blog.objects.all().filter(status='active', visible=True).order_by('catagories','-created_at')
        # As per Templates Views
        first_post = featured_obj.first()
        s_post = featured_obj
        last_post = featured_obj
        context={
            'post':post_obj,
            'f_post':featured_obj,
            'first':first_post,
            's_post':s_post,
            'last_post':last_post
            
        }
        return render(request, 'home/index.html',context)

# single blog views
class SingleBlogView(View):
    def get(self,request,id,*args,**kwargs):
        post_obj = get_object_or_404(Blog, id=id)
        post_obj.visit_count = post_obj.visit_count + 1
        post_obj.save()
        releted_post = Blog.objects.filter(author=post_obj.author).exclude(id=id).order_by('-id')[:4]
        # As per templates views 
        first_post = releted_post.first()
        last_post  = releted_post[1:]
        
        context ={
            'post':post_obj,
            'r_post':releted_post,
            'first':first_post,
            'last':last_post
        }
        return render(request,'blogs/post/single_blog.html', context)

# Catagory View
class CatagoryView(View):
    def get(self,request,slug,*args,**kwargs):
        catagory_obj = get_object_or_404(Catagory, slug=slug)
        #post = catagory_obj.blog_set.all().order_by('-id')
        post = Blog.objects.filter(catagories= catagory_obj,\
            status='active',visible=True)\
            .order_by('-created_at')
        popular = Blog.objects.filter(catagories= catagory_obj,\
            status='active',visible=True)\
            .annotate(post_count=Count('visit_count'))\
            .order_by('-visit_count')
        # as Per templates views
        featured_post = popular.first()
        popular_post = popular[1:6]
        # Pagination 
        paginator = Paginator(post, 3)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context ={
            'catagory':catagory_obj,
            'post':page_obj,
            'pop':popular_post,
            'f_post':featured_post,
        }
        return render(request,'blogs/category/category.html', context )

# tag View
class TagView(View):
    def get(self,request,id,*args,**kwargs):
        tag_obj = get_object_or_404(Tag, id=id)
        post = tag_obj.blog_set.all().order_by('-id')
        tag_count = post.count()
        context={
            'tag':tag_obj,
            'post':post,
            'tag_count':tag_count
        }
        return render(request,'home/tag.html',context)

# Subscribe Views
class SubsCribe(View):
    def post(self, request,*args,**kwargs):
        sub_obj = request.POST.get('subscribe')
        email = EmailSignUp.objects.filter(email=sub_obj)
        if email :
            messages.success(request,'You are already Subscribed , Thanks!')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            subscribe = EmailSignUp.objects.create(email=sub_obj)
            subscribe.save()
            messages.success(request,'Thanks for Subscribing')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

# search Views
class SearchView(View):
    def get(self,request,*args,**kwargs):
        search = request.GET['q']
        post = Blog.objects.filter(status='active',visible=True)
        if len(search) > 100:
            posts = post.none()
        else:
            posts = post.filter(
                Q(title__icontains=search) |
                Q(catagories__name__icontains=search) |
                Q(detail__icontains = search)
                
            )
        context ={
            'post':posts,
            'search':search
        }
        return render(request,'home/search.html', context)

# Comments View
class CommentView(View):
    def post(self,request,id, *args,**kwargs):
        post = get_object_or_404(Blog,id=id)
        name = request.POST.get('name')
        body = request.POST.get('body')
        comment_obj = Comment(post=post,name=name,body=body)
        comment_obj.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def test(request):
    catagory_obj = Catagory.objects.all()
    cat = Catagory.objects.all().count()
    lent = len(catagory_obj)
    #post = Catagory.blog_set.count()
    #post = Blog.objects.filter(catagories__icontains = catagory_obj).count()

    # src = https://able.bio/rhett/how-to-order-by-count-of-a-foreignkey-field-in-django--26y1ug1
    
    post = Catagory.objects.all() \
        .annotate(post_count=Count('blog'))\
        .order_by('-post_count')
    context = {
        'catagory':catagory_obj,
        'cat':cat,
        'lent':lent,
        'post':post
        
        
    }
    return render(request,'test.html', context)

crm/chatgpt/views.py
from django.shortcuts import render
from openai import Model
# Create your views here.
from crm.chatgpt.utils import ChatGpt

from django.http import HttpResponse
from django.views import View

class GptView(View):

    def get(self, request, *args, **kwargs):
        locals=ChatGpt.get_models()
        content={
            'data': locals
        }

        return render(request, 'gpt/gpt.html',content)

crm/quotes/views.py
from django.shortcuts import render
from django.shortcuts import redirect

# Create your views here.
from django.core.management import call_command
from crm.quotes.models  import Quotes
def qoutes(request):

    call_command('digitalocean_all_post')
    
    
    return redirect("/")

crm/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet
from django.views.generic import DetailView, RedirectView, UpdateView
from rest_framework.permissions import AllowAny

from .serializers import UserSerializer

from django.shortcuts import get_object_or_404
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer
from rest_framework.response import Response
from rest_framework.views import APIView


User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

class UserList(APIView):
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]

    template_name = 'users/User_list.html'
    permission_classes = [AllowAny]


    def get(self, request):
        # return Response({'Users': queryset})
    
        queryset = User.objects.filter(is_active=True).values('username','id','email','name')
        print(queryset)

        if request.accepted_renderer.format == 'html':
            # TemplateHTMLRenderer takes a context dict,
            # and additionally requires a 'template_name'.
            # It does not require serialization.
            data = {'users': queryset}
            return Response(data, template_name='users/User_list.html')

        # # JSONRenderer requires serialized data as normal.
        # serializer = UserSerializer(instance=queryset)
        # data = serializer.data
        data = {'users': queryset}

        return Response(data)
        


class UserDetail(APIView):
    model = User
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    # template_name = 'users/user_detail.html'
    permission_classes=[AllowAny]

    def get(self, request, id):
        if id:

            queryset = User.objects.filter(id=id).values('username','id','email','name')

            if request.accepted_renderer.format == 'html':
                # TemplateHTMLRenderer takes a context dict,
                # and additionally requires a 'template_name'.
                # It does not require serialization.
                # return Response(data, template_name='users/User_list.html')
                # serializer = UserSerializer(data)
                return Response({'data': queryset[0]},template_name='users/user_detail.html')
         
            return Response({'users': queryset})
        




        
        # else:
        #     serializer = UserSerializer()
        #     return Response({'serializer': serializer})

    # def post(self, request, pk):
    #     if pk:
    #         data = get_object_or_404(data, pk=pk)
    #         serializer = UserSerializer(data, data=request.data)
    #         if not serializer.is_valid():
    #             return Response({'serializer': serializer, 'data': data})
    #         serializer.save()
    #     else:
    #         serializer = UserSerializer(data=request.data)
    #         serializer.save()

    #     return redirect('../../licsoftware/')

crm/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

crm/templates/blogs/post/single_blog.html
{% extends 'home/base/base.html' %}
{% block title %} {{post.title }} | MultiBlogs {% endblock %}
{% block body %}
<div class="container">
	<div class="jumbotron jumbotron-fluid mb-3 pl-0 pt-0 pb-0 bg-white position-relative">
		<div class="h-100 tofront">
			<div class="row justify-content-between">
				<div class="col-md-6 pt-6 pb-6 pr-6 align-self-center">

								
			{% if messages %}
			<div class="messages" >
				{% for message in messages %}
					<div class="alert alert-primary" {% if message.tags %}
						 class="{{ message.tags }}"{% endif %}>{{ message }}
						 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						  </button>
					</div>
			
				{% endfor %}
			</div>
			{% endif %}

			<p class="text-uppercase font-weight-bold">
				<a class="text-danger" href="{% url 'blog:catagory' post.id %}">{{post.catagories}}</a>
			</p>
			<h1 class="display-4 secondfont  font-weight-bold">{{ post.title }}</h1>
			{% comment %} <p class="mb-3">
					Analysts told CNBC that the currency could hit anywhere between $1.35-$1.40 if the deal gets passed through the U.K. parliament.
			</p> {% endcomment %}
			<div class="row">

				<div class="col-md-3 pr-0">
					<img src="{{post.image_url }}">
				</div>
			</div>
			<div class="d-flex align-items-center">
			{% if p.author.author_image %}
				<img height="20" class="rounded-circle shadow" style="border-radius: 50%;" src="{{ p.author.author_image.url }}">
			{% else %}
				<img class="rounded-circle shadow" height="70" src="https://www.pngarts.com/files/11/Avatar-PNG-Transparent-Image.png" alt=""> 
			{% endif %}
				<small class="ml-2"> {{ post.author.author.username }} <span class="text-muted d-block">{{post.created_at | timesince }} ago ; {{post.visit_count }} views </span>
				</small>
			</div>
			</div>
			</div>
		</div>
	</div>



<div class="container pt-4 pb-4">
	<div class="row justify-content-center">
		<div class="col-lg-2 pr-4 mb-4 col-md-12">
			<div class="sticky-top text-center">
				<div class="text-muted">
					Share this
				</div>
				<div class="share d-inline-block">
					<!-- AddToAny BEGIN -->
					<div class="a2a_kit a2a_kit_size_32 a2a_default_style">
						<a class="a2a_dd" href="https://www.addtoany.com/share"></a>
						<a class="a2a_button_facebook"></a>
						<a class="a2a_button_twitter"></a>
					</div>
					<script async src="https://static.addtoany.com/menu/page.js"></script>
					<!-- AddToAny END -->
				</div>
			</div>
		</div>
		<div class="col-md-12 col-lg-8">
			<article class="article-post">
                <p>{{ post.detail|safe }}</p>
			</article>
			<div class="border p-5 bg-lightblue">
				<div class="row justify-content-between">
					<div class="col-md-5 mb-2 mb-md-0">
						<h5 class="font-weight-bold secondfont">Become a member</h5>
						 Get the latest news right in your inbox. We never spam!
					</div>
					<div class="col-md-7">
                        <form action="{% url 'blog:subscribe' %}" method="POST">
						<div class="row">
                            
                                {% csrf_token %}
							<div class="col-md-12">
								<input type="email" name='subscribe' class="form-control" placeholder="Enter your e-mail address" required>
							</div>
							<div class="col-md-12 mt-2">
								<button type="submit" class="btn btn-success btn-block">Subscribe</button>
							</div>
                        
						</div>
                    </form>
					</div>
				</div>
			</div>

			<form style="margin-top:50px;" action="{% url 'blog:comment' post.id  %}" method="POST">
				{% csrf_token %}
				<div class="row form-group">
					<div class="col">
						<input type="text" name='name' class="form-control" placeholder="Your Name">
					</div>
				</div>
				<div class="form-group">
					<textarea class="form-control" name='body' id="exampleFormControlTextarea1" rows="4"></textarea>
				</div>
				<button type="submit" class="btn btn-primary btn-round">Submit Comment </button>
			</form>
			<br>


				{% for p in post.comments.all  reversed %}
				{% if forloop.counter|divisibleby:2 %}
				<div style="border-radius: 10px; margin: 5px; padding: 25px; background-color: #d8d8d8; ">
					<p><strong>{{ p.name }}</strong> at {{ p.created_at }}</p>
					<p style="padding: 20px; background-color: #f1f1f1; border-radius: 7px; border:0.5px solid #c5c5c5">{{ p.body }}</p>
				</div>
				{% else %}
				<div style="border-radius: 10px; margin: 5px; padding: 25px; background-color: #b3d3c0;">
					<p><strong>{{ p.name }}</strong> at {{ p.created_at }}</p>
					<p style="padding: 20px; background-color: #c5e6d3; border-radius: 7px; border:0.5px solid #c5c5c5">{{ p.body }}</p>
				</div>
				{% endif %}
				{% endfor %}
		</div>
	</div>
</div>



<div class=" pt-4 pb-4">
	<h5 class="font-weight-bold spanborder"><span>Read next</span></h5>
	
	<div class="row">
		
		<div class="col-lg-6">
			
			<div class="card border-0 mb-4 box-shadow h-xl-300">
				<div style="background-image: url(./assets/img/demo/3.jpg); ">
					<img src="{{ first.image_url }}" style="height: 200px; background-size: cover; background-repeat: no-repeat; width: 100%;" alt="">
				</div>
				<div class="card-body px-0 pb-0 d-flex flex-column align-items-start">
					<h2 class="h4 font-weight-bold">
					{% comment %} <a class="text-dark" href="{% url 'blog:single_blog' first.id %}"> {{ first.title}} </a> {% endcomment %}
					</h2>
					<p class="card-text">
						{{first.detail|truncatechars:150 |safe}}
					</p>
					<div>
						<small class="d-block">
						{% if p.author.author_image %}
						    <img height="20" class="rounded-circle shadow" style="border-radius: 50%;" src="{{ p.author.author_image.url }}">
                        {% else %}
                            <img class="rounded-circle shadow" height="20" src="https://www.pngarts.com/files/11/Avatar-PNG-Transparent-Image.png" alt=""> 
                        {% endif %}
						<a class="text-muted" href="./author.html">{{first.author.author.username}}</a></small>
						<small class="text-muted">{{ first.created_at | timesince }} ago .  {{first.visit_count}} views</small>
					</div>
				</div>
			</div>
			
		</div>
		
		<div class="col-lg-6">
			
			<div class="flex-md-row mb-4 box-shadow h-xl-300">
				{% for p in last %}
				<div class="mb-3 d-flex align-items-center">
					<img height="80" src="{{p.image_url}}">
					<div class="pl-3">
						<h2 class="mb-2 h6 font-weight-bold">
						<a class="text-dark" href="{% url 'blog:single_blog' p.id %}">{{p.title}}</a>
						</h2>
						<div class="card-text text-muted small">
						{% if p.author.author_image %}
						    <img height="20" class="rounded-circle shadow" style="border-radius: 50%;" src="{{ p.author.author_image.url }}">
                        {% else %}
                            <img class="rounded-circle shadow" height="20" src="https://www.pngarts.com/files/11/Avatar-PNG-Transparent-Image.png" alt=""> 
                        {% endif %}
                        {{ p.author.author.username }} in <a class="text-dark" href="{% url 'blog:catagory' p.id %}">{{p.catagories }} </a>
						
						</div>
						<small class="text-muted">{{ p.created_at | timesince }} ago .  {{p.visit_count}} views</small>
					</div>
				</div>
				{% endfor %}
			</div>
			
			
		</div>
		
		
	</div>
	
</div>
</div>

<!-- messages section -->


{% endblock %}